### ISSUE TITLE
로그아웃 할 때 토큰 검증여부 토의 필요

### ISSUE THREAD

**Issue by kimchijinju** [august-thirty-first/backend#15]
로그아웃 할 때 토큰 검증여부 토의 필요

_Originally posted by @yoonkiung in https://github.com/august-thirty-first/backend/issues/14#issuecomment-1655226682_

**Comment by jari46** [comment]
[부가설명]
로그아웃 처리를 토큰이 있는 사람만 back에서 처리해줄 것인지, 토큰이 없으면 막을 것인지 결정해야 합니다. (?)
두 경우 모두 login 페이지로 리다이렉트됩니다.

**Comment by kimchijinju** [comment]
임시 토큰을 들고 로그아웃 할 때
정규 토큰을 들고 로그아웃 할 때
두 경우에 대해서 생각해봐야 합니다
