### ISSUE TITLE
백엔드에서 redirect 하는 문제

### ISSUE THREAD

**Issue by kimchijinju** [august-thirty-first/backend#18]
## 버그 상황
로그아웃 작동 후 백엔드에서 front url로 redirect를 하는데, 이걸 front에서 처리하도록 변경해야 합니다.

## 예상 시간

**Comment by jari46** [comment]
[여기](https://www.figma.com/file/ioTXPKLdSv9FTjdVGiWXqh/Untitled?type=whiteboard&node-id=0%3A1&t=DiHWVGJchdajJEhM-1)에 경우 표시 해두었어요
